default: &default
    adapter: postgresql
    encoding: unicode
    username: <%= ENV["DB_USER"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
    <<: *default
    database: "clari_next"

test:
    <<: *default
    database: clari_test

production:
    <<: *default
    host: postgres
    database: clari_production